#################
# 语音识别器配置 #
#################

# 模型目录本地路径
model_dir_path: models/listener
# 音频采样率
sample_rate: 16000
# 识别块大小
chunk_size: 16
# VAD检测阈值
vad_threshold: 0.7
# VAD采样窗口帧大小
vad_window_frame_size: 32